### ISSUE TITLE
Windows cmake error

### ISSUE THREAD

**Issue by wizofe** [AuthorityFX/afx-nuke-plugins#5]
I am getting this error. Mind you, I don't have `Nuke` on the machine that I am compiling this so that may be related? I saw that there are requirements in the beginning but it's not clear if the requirements are for running or compiling the plugin.

My plan was to compile the plugin inside a VM and release then to a different machine as that makes the process more reproducible.

That's the log: 

```
C:\Users\IEUser\afx-nuke-plugins\build>cmake -G "Visual Studio 10 2010 Win64" ..
CMake Error at cmake/Modules/FindNuke.cmake:25 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:53 (find_package)
 
 
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Nuke (missing: NUKE_ROOT Nuke_INCLUDE_DIR Nuke_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindNuke.cmake:54 (find_package_handle_standard_args)
  CMakeLists.txt:53 (find_package)
 
 
-- Configuring incomplete, errors occurred!
See also "C:/Users/IEUser/afx-nuke-plugins/build/CMakeFiles/CMakeOutput.log".
```

**Comment by AuthorityFX** [comment]
Look in this file to see what is needed https://github.com/AuthorityFX/afx-nuke-plugins/blob/master/cmake/Modules/FindNuke.cmake

You just need the NDK on the VM.
